#!/bin/bash

# C. U. - Computer Utilizator
# by fde_capu
#
#  bu_vim 
#
# Copies the custom x_header to Vim.

cp ~/_/cu/zim/.vimrc ~/.vimrc
cp -r ~/_/cu/zim/.vim/* ~/.vim
mkdir -f ~/.vim/backups
mkdir -f ~/.vim/swaps
